name: OBS build script
description: This action builds packages by calling `pbuild` from the [OBS build script](https://github.com/openSUSE/obs-build).
branding:
  icon: package
  color: green

inputs:
  path:
    description: 'Folder path in which obs-build is executed'
    required: false
    default: '.'
  vm-type:
    description: 'Type of VM to use: chroot, kvm, or qemu'
    required: false
    default: 'kvm'
  dist:
    description: 'Name of distribution from [known configs](https://github.com/openSUSE/obs-build/tree/20240913/configs), a filename, or an URL to config file'
    required: false
    default: 'sl15.6'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo "${GITHUB_ACTION_PATH}/src/setup.sh"
    - shell: bash
      run: |
        sudo "${GITHUB_ACTION_PATH}/src/run.py" --vm-type="${{ inputs.vm-type }}" "${{ inputs.path }}"
