name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test with default options
        uses: ./
        with:
          path: ./test/packages/rpm/simple

      - name: Test with non-default options
        uses: ./
        with:
          path: ./test/packages/rpm/simple
          vm-type: kvm
          dist: /usr/lib/build/configs/sl15.6.conf

  test:
    name: Test
    runs-on: ubuntu-24.04
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo ./src/setup.sh
          sudo ./test/setup.sh

      - name: Run tests
        run: |
          sudo WORKSPACE="${{ github.workspace }}" ./test/test.sh
